<?php
/**
 * CatalogApi
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\marketingsolutions\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - MarketingSolutions
 *
 * The version of the OpenAPI document: Experimental
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\marketingsolutions\experimental\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use criteo\api\marketingsolutions\experimental\ApiException;
use criteo\api\marketingsolutions\experimental\Configuration;
use criteo\api\marketingsolutions\experimental\HeaderSelector;
use criteo\api\marketingsolutions\experimental\ObjectSerializer;

/**
 * CatalogApi Class Doc Comment
 *
 * @category Class
 * @package  criteo\api\marketingsolutions\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CatalogApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getCatalogIngestionReportSummary' => [
            'application/json',
        ],
        'getCatalogIngestionReports' => [
            'application/json',
        ],
        'getCatalogMerchantStats' => [
            'application/json',
        ],
        'getCatalogProductsBatchReport' => [
            'application/json',
        ],
        'submitCatalogProductsBatch' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getCatalogIngestionReportSummary
     *
     * /experimental/marketing-solutions/catalog/ingestion/{ingestion-id}/reports/summary
     *
     * @param  string $ingestion_id Identifies the catalog ingestion to report on. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReportSummary'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse
     */
    public function getCatalogIngestionReportSummary($ingestion_id, string $contentType = self::contentTypes['getCatalogIngestionReportSummary'][0])
    {
        list($response) = $this->getCatalogIngestionReportSummaryWithHttpInfo($ingestion_id, $contentType);
        return $response;
    }

    /**
     * Operation getCatalogIngestionReportSummaryWithHttpInfo
     *
     * /experimental/marketing-solutions/catalog/ingestion/{ingestion-id}/reports/summary
     *
     * @param  string $ingestion_id Identifies the catalog ingestion to report on. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReportSummary'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCatalogIngestionReportSummaryWithHttpInfo($ingestion_id, string $contentType = self::contentTypes['getCatalogIngestionReportSummary'][0])
    {
        $request = $this->getCatalogIngestionReportSummaryRequest($ingestion_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCatalogIngestionReportSummaryAsync
     *
     * /experimental/marketing-solutions/catalog/ingestion/{ingestion-id}/reports/summary
     *
     * @param  string $ingestion_id Identifies the catalog ingestion to report on. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReportSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogIngestionReportSummaryAsync($ingestion_id, string $contentType = self::contentTypes['getCatalogIngestionReportSummary'][0])
    {
        return $this->getCatalogIngestionReportSummaryAsyncWithHttpInfo($ingestion_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCatalogIngestionReportSummaryAsyncWithHttpInfo
     *
     * /experimental/marketing-solutions/catalog/ingestion/{ingestion-id}/reports/summary
     *
     * @param  string $ingestion_id Identifies the catalog ingestion to report on. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReportSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogIngestionReportSummaryAsyncWithHttpInfo($ingestion_id, string $contentType = self::contentTypes['getCatalogIngestionReportSummary'][0])
    {
        $returnType = '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionSummaryResponse';
        $request = $this->getCatalogIngestionReportSummaryRequest($ingestion_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCatalogIngestionReportSummary'
     *
     * @param  string $ingestion_id Identifies the catalog ingestion to report on. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReportSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCatalogIngestionReportSummaryRequest($ingestion_id, string $contentType = self::contentTypes['getCatalogIngestionReportSummary'][0])
    {

        // verify the required parameter 'ingestion_id' is set
        if ($ingestion_id === null || (is_array($ingestion_id) && count($ingestion_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ingestion_id when calling getCatalogIngestionReportSummary'
            );
        }


        $resourcePath = '/experimental/marketing-solutions/catalog/ingestion/{ingestion-id}/reports/summary';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($ingestion_id !== null) {
            $resourcePath = str_replace(
                '{' . 'ingestion-id' . '}',
                ObjectSerializer::toPathValue($ingestion_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCatalogIngestionReports
     *
     * /experimental/marketing-solutions/catalog/merchants/{merchant-id}/ingestion/reports
     *
     * @param  string $merchant_id Identifies the merchant whose catalog ingestions are reported. (required)
     * @param  int $limit Maximum number of ingestion reports returned in the page. (optional, default to 25)
     * @param  int $offset Index of the first ingestion report of the page, used to page through the collection. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReports'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse
     */
    public function getCatalogIngestionReports($merchant_id, $limit = 25, $offset = 0, string $contentType = self::contentTypes['getCatalogIngestionReports'][0])
    {
        list($response) = $this->getCatalogIngestionReportsWithHttpInfo($merchant_id, $limit, $offset, $contentType);
        return $response;
    }

    /**
     * Operation getCatalogIngestionReportsWithHttpInfo
     *
     * /experimental/marketing-solutions/catalog/merchants/{merchant-id}/ingestion/reports
     *
     * @param  string $merchant_id Identifies the merchant whose catalog ingestions are reported. (required)
     * @param  int $limit Maximum number of ingestion reports returned in the page. (optional, default to 25)
     * @param  int $offset Index of the first ingestion report of the page, used to page through the collection. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReports'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCatalogIngestionReportsWithHttpInfo($merchant_id, $limit = 25, $offset = 0, string $contentType = self::contentTypes['getCatalogIngestionReports'][0])
    {
        $request = $this->getCatalogIngestionReportsRequest($merchant_id, $limit, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCatalogIngestionReportsAsync
     *
     * /experimental/marketing-solutions/catalog/merchants/{merchant-id}/ingestion/reports
     *
     * @param  string $merchant_id Identifies the merchant whose catalog ingestions are reported. (required)
     * @param  int $limit Maximum number of ingestion reports returned in the page. (optional, default to 25)
     * @param  int $offset Index of the first ingestion report of the page, used to page through the collection. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReports'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogIngestionReportsAsync($merchant_id, $limit = 25, $offset = 0, string $contentType = self::contentTypes['getCatalogIngestionReports'][0])
    {
        return $this->getCatalogIngestionReportsAsyncWithHttpInfo($merchant_id, $limit, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCatalogIngestionReportsAsyncWithHttpInfo
     *
     * /experimental/marketing-solutions/catalog/merchants/{merchant-id}/ingestion/reports
     *
     * @param  string $merchant_id Identifies the merchant whose catalog ingestions are reported. (required)
     * @param  int $limit Maximum number of ingestion reports returned in the page. (optional, default to 25)
     * @param  int $offset Index of the first ingestion report of the page, used to page through the collection. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReports'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogIngestionReportsAsyncWithHttpInfo($merchant_id, $limit = 25, $offset = 0, string $contentType = self::contentTypes['getCatalogIngestionReports'][0])
    {
        $returnType = '\criteo\api\marketingsolutions\experimental\Model\CatalogIngestionReportListResponse';
        $request = $this->getCatalogIngestionReportsRequest($merchant_id, $limit, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCatalogIngestionReports'
     *
     * @param  string $merchant_id Identifies the merchant whose catalog ingestions are reported. (required)
     * @param  int $limit Maximum number of ingestion reports returned in the page. (optional, default to 25)
     * @param  int $offset Index of the first ingestion report of the page, used to page through the collection. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogIngestionReports'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCatalogIngestionReportsRequest($merchant_id, $limit = 25, $offset = 0, string $contentType = self::contentTypes['getCatalogIngestionReports'][0])
    {

        // verify the required parameter 'merchant_id' is set
        if ($merchant_id === null || (is_array($merchant_id) && count($merchant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $merchant_id when calling getCatalogIngestionReports'
            );
        }

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CatalogApi.getCatalogIngestionReports, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CatalogApi.getCatalogIngestionReports, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/experimental/marketing-solutions/catalog/merchants/{merchant-id}/ingestion/reports';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($merchant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'merchant-id' . '}',
                ObjectSerializer::toPathValue($merchant_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCatalogMerchantStats
     *
     * /experimental/catalog/stats/merchants/{merchant-id}
     *
     * @param  string $merchant_id merchant-id to get (required)
     * @param  int $last_num_hours the last number of hours (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogMerchantStats'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse
     */
    public function getCatalogMerchantStats($merchant_id, $last_num_hours = null, string $contentType = self::contentTypes['getCatalogMerchantStats'][0])
    {
        list($response) = $this->getCatalogMerchantStatsWithHttpInfo($merchant_id, $last_num_hours, $contentType);
        return $response;
    }

    /**
     * Operation getCatalogMerchantStatsWithHttpInfo
     *
     * /experimental/catalog/stats/merchants/{merchant-id}
     *
     * @param  string $merchant_id merchant-id to get (required)
     * @param  int $last_num_hours the last number of hours (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogMerchantStats'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCatalogMerchantStatsWithHttpInfo($merchant_id, $last_num_hours = null, string $contentType = self::contentTypes['getCatalogMerchantStats'][0])
    {
        $request = $this->getCatalogMerchantStatsRequest($merchant_id, $last_num_hours, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCatalogMerchantStatsAsync
     *
     * /experimental/catalog/stats/merchants/{merchant-id}
     *
     * @param  string $merchant_id merchant-id to get (required)
     * @param  int $last_num_hours the last number of hours (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogMerchantStats'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogMerchantStatsAsync($merchant_id, $last_num_hours = null, string $contentType = self::contentTypes['getCatalogMerchantStats'][0])
    {
        return $this->getCatalogMerchantStatsAsyncWithHttpInfo($merchant_id, $last_num_hours, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCatalogMerchantStatsAsyncWithHttpInfo
     *
     * /experimental/catalog/stats/merchants/{merchant-id}
     *
     * @param  string $merchant_id merchant-id to get (required)
     * @param  int $last_num_hours the last number of hours (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogMerchantStats'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogMerchantStatsAsyncWithHttpInfo($merchant_id, $last_num_hours = null, string $contentType = self::contentTypes['getCatalogMerchantStats'][0])
    {
        $returnType = '\criteo\api\marketingsolutions\experimental\Model\StatisticsOkResponse';
        $request = $this->getCatalogMerchantStatsRequest($merchant_id, $last_num_hours, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCatalogMerchantStats'
     *
     * @param  string $merchant_id merchant-id to get (required)
     * @param  int $last_num_hours the last number of hours (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogMerchantStats'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCatalogMerchantStatsRequest($merchant_id, $last_num_hours = null, string $contentType = self::contentTypes['getCatalogMerchantStats'][0])
    {

        // verify the required parameter 'merchant_id' is set
        if ($merchant_id === null || (is_array($merchant_id) && count($merchant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $merchant_id when calling getCatalogMerchantStats'
            );
        }



        $resourcePath = '/experimental/catalog/stats/merchants/{merchant-id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $last_num_hours,
            'lastNumHours', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($merchant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'merchant-id' . '}',
                ObjectSerializer::toPathValue($merchant_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCatalogProductsBatchReport
     *
     * /experimental/catalog/products/batch/report/{operation-token}
     *
     * @param  string $operation_token The token returned by the batch endpoint. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogProductsBatchReport'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \criteo\api\marketingsolutions\experimental\Model\ReportOkResponse
     */
    public function getCatalogProductsBatchReport($operation_token, string $contentType = self::contentTypes['getCatalogProductsBatchReport'][0])
    {
        list($response) = $this->getCatalogProductsBatchReportWithHttpInfo($operation_token, $contentType);
        return $response;
    }

    /**
     * Operation getCatalogProductsBatchReportWithHttpInfo
     *
     * /experimental/catalog/products/batch/report/{operation-token}
     *
     * @param  string $operation_token The token returned by the batch endpoint. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogProductsBatchReport'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \criteo\api\marketingsolutions\experimental\Model\ReportOkResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCatalogProductsBatchReportWithHttpInfo($operation_token, string $contentType = self::contentTypes['getCatalogProductsBatchReport'][0])
    {
        $request = $this->getCatalogProductsBatchReportRequest($operation_token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\criteo\api\marketingsolutions\experimental\Model\ReportOkResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\criteo\api\marketingsolutions\experimental\Model\ReportOkResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\criteo\api\marketingsolutions\experimental\Model\ReportOkResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\criteo\api\marketingsolutions\experimental\Model\ReportOkResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\criteo\api\marketingsolutions\experimental\Model\ReportOkResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCatalogProductsBatchReportAsync
     *
     * /experimental/catalog/products/batch/report/{operation-token}
     *
     * @param  string $operation_token The token returned by the batch endpoint. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogProductsBatchReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogProductsBatchReportAsync($operation_token, string $contentType = self::contentTypes['getCatalogProductsBatchReport'][0])
    {
        return $this->getCatalogProductsBatchReportAsyncWithHttpInfo($operation_token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCatalogProductsBatchReportAsyncWithHttpInfo
     *
     * /experimental/catalog/products/batch/report/{operation-token}
     *
     * @param  string $operation_token The token returned by the batch endpoint. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogProductsBatchReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogProductsBatchReportAsyncWithHttpInfo($operation_token, string $contentType = self::contentTypes['getCatalogProductsBatchReport'][0])
    {
        $returnType = '\criteo\api\marketingsolutions\experimental\Model\ReportOkResponse';
        $request = $this->getCatalogProductsBatchReportRequest($operation_token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCatalogProductsBatchReport'
     *
     * @param  string $operation_token The token returned by the batch endpoint. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogProductsBatchReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCatalogProductsBatchReportRequest($operation_token, string $contentType = self::contentTypes['getCatalogProductsBatchReport'][0])
    {

        // verify the required parameter 'operation_token' is set
        if ($operation_token === null || (is_array($operation_token) && count($operation_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $operation_token when calling getCatalogProductsBatchReport'
            );
        }


        $resourcePath = '/experimental/catalog/products/batch/report/{operation-token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($operation_token !== null) {
            $resourcePath = str_replace(
                '{' . 'operation-token' . '}',
                ObjectSerializer::toPathValue($operation_token),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation submitCatalogProductsBatch
     *
     * /experimental/catalog/products/batch
     *
     * @param  \criteo\api\marketingsolutions\experimental\Model\ProductsCustomBatchRequest $products_custom_batch_request products_custom_batch_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCatalogProductsBatch'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse
     */
    public function submitCatalogProductsBatch($products_custom_batch_request, string $contentType = self::contentTypes['submitCatalogProductsBatch'][0])
    {
        list($response) = $this->submitCatalogProductsBatchWithHttpInfo($products_custom_batch_request, $contentType);
        return $response;
    }

    /**
     * Operation submitCatalogProductsBatchWithHttpInfo
     *
     * /experimental/catalog/products/batch
     *
     * @param  \criteo\api\marketingsolutions\experimental\Model\ProductsCustomBatchRequest $products_custom_batch_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCatalogProductsBatch'] to see the possible values for this operation
     *
     * @throws \criteo\api\marketingsolutions\experimental\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitCatalogProductsBatchWithHttpInfo($products_custom_batch_request, string $contentType = self::contentTypes['submitCatalogProductsBatch'][0])
    {
        $request = $this->submitCatalogProductsBatchRequest($products_custom_batch_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 202:
                    if ('\criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation submitCatalogProductsBatchAsync
     *
     * /experimental/catalog/products/batch
     *
     * @param  \criteo\api\marketingsolutions\experimental\Model\ProductsCustomBatchRequest $products_custom_batch_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCatalogProductsBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitCatalogProductsBatchAsync($products_custom_batch_request, string $contentType = self::contentTypes['submitCatalogProductsBatch'][0])
    {
        return $this->submitCatalogProductsBatchAsyncWithHttpInfo($products_custom_batch_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation submitCatalogProductsBatchAsyncWithHttpInfo
     *
     * /experimental/catalog/products/batch
     *
     * @param  \criteo\api\marketingsolutions\experimental\Model\ProductsCustomBatchRequest $products_custom_batch_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCatalogProductsBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitCatalogProductsBatchAsyncWithHttpInfo($products_custom_batch_request, string $contentType = self::contentTypes['submitCatalogProductsBatch'][0])
    {
        $returnType = '\criteo\api\marketingsolutions\experimental\Model\BatchAcceptedResponse';
        $request = $this->submitCatalogProductsBatchRequest($products_custom_batch_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'submitCatalogProductsBatch'
     *
     * @param  \criteo\api\marketingsolutions\experimental\Model\ProductsCustomBatchRequest $products_custom_batch_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCatalogProductsBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function submitCatalogProductsBatchRequest($products_custom_batch_request, string $contentType = self::contentTypes['submitCatalogProductsBatch'][0])
    {

        // verify the required parameter 'products_custom_batch_request' is set
        if ($products_custom_batch_request === null || (is_array($products_custom_batch_request) && count($products_custom_batch_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $products_custom_batch_request when calling submitCatalogProductsBatch'
            );
        }


        $resourcePath = '/experimental/catalog/products/batch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($products_custom_batch_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($products_custom_batch_request));
            } else {
                $httpBody = $products_custom_batch_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
