<?php
/**
 * VastTagAttributes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\marketingsolutions\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - MarketingSolutions
 *
 * The version of the OpenAPI document: Experimental
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\marketingsolutions\experimental\Model;

use \ArrayAccess;
use \criteo\api\marketingsolutions\experimental\ObjectSerializer;

/**
 * VastTagAttributes Class Doc Comment
 *
 * @category Class
 * @description The attributes specific to VastTag creatives (read model).  Most fields are derived by parsing the VAST tag and are read-only.
 * @package  criteo\api\marketingsolutions\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VastTagAttributes implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'VastTagAttributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'has_vpaid' => 'bool',
        'is_skippable' => 'bool',
        'mime_types' => 'string[]',
        'vast_tag_url' => 'string',
        'vast_version' => 'string',
        'video_duration_ms' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'has_vpaid' => null,
        'is_skippable' => null,
        'mime_types' => null,
        'vast_tag_url' => null,
        'vast_version' => null,
        'video_duration_ms' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'has_vpaid' => true,
		'is_skippable' => true,
		'mime_types' => true,
		'vast_tag_url' => true,
		'vast_version' => true,
		'video_duration_ms' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'has_vpaid' => 'hasVpaid',
        'is_skippable' => 'isSkippable',
        'mime_types' => 'mimeTypes',
        'vast_tag_url' => 'vastTagUrl',
        'vast_version' => 'vastVersion',
        'video_duration_ms' => 'videoDurationMs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'has_vpaid' => 'setHasVpaid',
        'is_skippable' => 'setIsSkippable',
        'mime_types' => 'setMimeTypes',
        'vast_tag_url' => 'setVastTagUrl',
        'vast_version' => 'setVastVersion',
        'video_duration_ms' => 'setVideoDurationMs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'has_vpaid' => 'getHasVpaid',
        'is_skippable' => 'getIsSkippable',
        'mime_types' => 'getMimeTypes',
        'vast_tag_url' => 'getVastTagUrl',
        'vast_version' => 'getVastVersion',
        'video_duration_ms' => 'getVideoDurationMs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('has_vpaid', $data ?? [], null);
        $this->setIfExists('is_skippable', $data ?? [], null);
        $this->setIfExists('mime_types', $data ?? [], null);
        $this->setIfExists('vast_tag_url', $data ?? [], null);
        $this->setIfExists('vast_version', $data ?? [], null);
        $this->setIfExists('video_duration_ms', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets has_vpaid
     *
     * @return bool|null
     */
    public function getHasVpaid()
    {
        return $this->container['has_vpaid'];
    }

    /**
     * Sets has_vpaid
     *
     * @param bool|null $has_vpaid Whether the tag contains a VPAID unit (vpaid y/n). Derived from the tag. VPAID is a deprecated  interactivity standard; this flag is recorded for information but interactive playback is not guaranteed.
     *
     * @return self
     */
    public function setHasVpaid($has_vpaid)
    {
        if (is_null($has_vpaid)) {
            array_push($this->openAPINullablesSetToNull, 'has_vpaid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('has_vpaid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['has_vpaid'] = $has_vpaid;

        return $this;
    }

    /**
     * Gets is_skippable
     *
     * @return bool|null
     */
    public function getIsSkippable()
    {
        return $this->container['is_skippable'];
    }

    /**
     * Sets is_skippable
     *
     * @param bool|null $is_skippable Whether the video is skippable. Derived from the tag.
     *
     * @return self
     */
    public function setIsSkippable($is_skippable)
    {
        if (is_null($is_skippable)) {
            array_push($this->openAPINullablesSetToNull, 'is_skippable');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_skippable', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_skippable'] = $is_skippable;

        return $this;
    }

    /**
     * Gets mime_types
     *
     * @return string[]|null
     */
    public function getMimeTypes()
    {
        return $this->container['mime_types'];
    }

    /**
     * Sets mime_types
     *
     * @param string[]|null $mime_types The supported media-file mime types (e.g. \"video/mp4\"). Derived from the tag.
     *
     * @return self
     */
    public function setMimeTypes($mime_types)
    {
        if (is_null($mime_types)) {
            array_push($this->openAPINullablesSetToNull, 'mime_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mime_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mime_types'] = $mime_types;

        return $this;
    }

    /**
     * Gets vast_tag_url
     *
     * @return string|null
     */
    public function getVastTagUrl()
    {
        return $this->container['vast_tag_url'];
    }

    /**
     * Sets vast_tag_url
     *
     * @param string|null $vast_tag_url The VAST tag URL (a hosted VAST XML endpoint).
     *
     * @return self
     */
    public function setVastTagUrl($vast_tag_url)
    {
        if (is_null($vast_tag_url)) {
            array_push($this->openAPINullablesSetToNull, 'vast_tag_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('vast_tag_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['vast_tag_url'] = $vast_tag_url;

        return $this;
    }

    /**
     * Gets vast_version
     *
     * @return string|null
     */
    public function getVastVersion()
    {
        return $this->container['vast_version'];
    }

    /**
     * Sets vast_version
     *
     * @param string|null $vast_version The VAST version declared by the tag (e.g. \"4.2\"). Derived from the tag.
     *
     * @return self
     */
    public function setVastVersion($vast_version)
    {
        if (is_null($vast_version)) {
            array_push($this->openAPINullablesSetToNull, 'vast_version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('vast_version', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['vast_version'] = $vast_version;

        return $this;
    }

    /**
     * Gets video_duration_ms
     *
     * @return float|null
     */
    public function getVideoDurationMs()
    {
        return $this->container['video_duration_ms'];
    }

    /**
     * Sets video_duration_ms
     *
     * @param float|null $video_duration_ms The video duration in milliseconds. Derived from the tag.
     *
     * @return self
     */
    public function setVideoDurationMs($video_duration_ms)
    {
        if (is_null($video_duration_ms)) {
            array_push($this->openAPINullablesSetToNull, 'video_duration_ms');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('video_duration_ms', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['video_duration_ms'] = $video_duration_ms;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


